function f = system_f(theta_1,theta_2,u_k,x_1k,x_2k)
%SYSTEM_F
%    F = SYSTEM_F(THETA_1,THETA_2,U_K,X_1K,X_2K)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Mar-2025 20:56:08

f = [x_1k+(u_k.*(x_1k./2.0+1.0./2.0))./2.0e+1-(theta_1.*x_2k)./2.0e+1;x_2k-(u_k.*(x_2k.*2.0-1.0./2.0))./2.0e+1+(theta_2.*x_1k)./2.0e+1];
end
