function B = jacobian_B(x_1k,x_2k)
%jacobian_B
%    B = jacobian_B(X_1K,X_2K)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    25-Feb-2025 10:42:07

B = [x_1k./4.0e+1+1.0./4.0e+1;x_2k.*(-1.0./1.0e+1)+1.0./4.0e+1];
end
