function A = jacobian_A(theta_1,theta_2,u_k)
%jacobian_A
%    A = jacobian_A(THETA_1,THETA_2,U_K)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Mar-2025 16:15:52

A = reshape([u_k./4.0e+1+1.0,theta_2./2.0e+1,theta_1.*(-1.0./2.0e+1),u_k.*(-1.0./1.0e+1)+1.0],[2,2]);
end
