function w_Theta = uncertainty_w_Theta(eta_t,z1,z2)
%uncertainty_w_Theta
%    w_Theta = uncertainty_w_Theta(ETA_T,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Mar-2025 20:38:02

t2 = z1.*6.131811046861033e+1;
t3 = z2.*6.131811046861033e+1;
t4 = z1.*2.129014281432485e+2;
t6 = z2.*2.266033560822537e+1;
t7 = -t6;
t8 = t3+t4;
t10 = t2+t6;
t13 = z1.*(t3-t4).*(-1.0./2.0e+1);
t11 = t2+t7;
t12 = (t8.*z1)./2.0e+1;
t14 = (t10.*z2)./2.0e+1;
t15 = (t11.*z2)./2.0e+1;
t17 = t12+t14;
t16 = -t15;
t19 = sqrt(t17);
t18 = t13+t16;
t20 = eta_t.*t19;
t21 = sqrt(t18);
t22 = eta_t.*t21;
w_Theta = [t20;t22;t20;t22];
end
