function w_delta_Theta_D = uncertainty_w_deltaThetaD(eta_t,s,z1,z2)
%uncertainty_w_deltaThetaD
%    w_delta_Theta_D = uncertainty_w_deltaThetaD(ETA_T,S,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Mar-2025 15:06:54

t2 = z2.*2.266033568603785e+1;
t3 = z1.*6.13181106869413e+1;
t4 = z2.*6.13181106869413e+1;
t5 = z1.*2.129014288891666e+2;
t8 = eta_t.*s.*1.024999999924821e-1;
t9 = t2+t3;
t10 = t4+t5;
t16 = z1.*(t4-t5).*(-1.0./2.0e+1);
t17 = (z2.*(t2-t3))./2.0e+1;
t13 = (t9.*z2)./2.0e+1;
t14 = (t10.*z1)./2.0e+1;
t19 = t16+t17+1.0e-6;
t18 = t13+t14+1.0e-6;
t22 = sqrt(t19);
t20 = sqrt(t18);
t23 = eta_t.*t22;
t21 = eta_t.*t20;
t25 = t8+t23+1.790989929745436e-5;
t24 = t8+t21+1.790989929745436e-5;
w_delta_Theta_D = [t24;t25;t24;t25];
end
