function w_delta_Theta_D = uncertainty_w_deltaThetaD(eta_t,s,z1,z2)
%uncertainty_w_deltaThetaD
%    w_delta_Theta_D = uncertainty_w_deltaThetaD(ETA_T,S,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    22-Feb-2025 21:38:31

t2 = z1.*5.000000010115778e-2;
t3 = z2.*5.000000010115778e-2;
t5 = z1.*2.14275183111301e-11;
t6 = z2.*2.14275183111301e-11;
t8 = eta_t.*s.*1.048569076184619e-12;
t7 = -t6;
t9 = t3+t5;
t10 = t2+t6;
t17 = (z2.*(t3-t5))./2.0e+1;
t12 = t2+t7;
t13 = (t10.*z1)./2.0e+1;
t14 = (t9.*z2)./2.0e+1;
t15 = (t12.*z1)./2.0e+1;
t18 = t13+t14+1.0e-6;
t19 = t15+t17+1.0e-6;
t20 = sqrt(t18);
t21 = eta_t.*t20;
t22 = sqrt(t19);
t23 = eta_t.*t22;
t24 = t8+t21+5.000000012258531e-9;
t25 = t8+t23+5.000000012258531e-9;
w_delta_Theta_D = [t24;t25;t24;t25];
end
