function w_Theta = uncertainty_w_Theta(eta_t,z1,z2)
%uncertainty_w_Theta
%    w_Theta = uncertainty_w_Theta(ETA_T,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Mar-2025 11:24:29

t2 = z2.*2.266033568603785e+1;
t3 = z1.*6.13181106869413e+1;
t4 = z2.*6.13181106869413e+1;
t5 = z1.*2.129014288891666e+2;
t8 = t2+t3;
t9 = t4+t5;
t15 = z1.*(t4-t5).*(-1.0./2.0e+1);
t16 = (z2.*(t2-t3))./2.0e+1;
t12 = (t8.*z2)./2.0e+1;
t13 = (t9.*z1)./2.0e+1;
t18 = t15+t16;
t17 = t12+t13;
t21 = sqrt(t18);
t19 = sqrt(t17);
t22 = eta_t.*t21;
t20 = eta_t.*t19;
w_Theta = [t20;t22;t20;t22];
end
