function w_Theta_D = uncertainty_w_ThetaD(eta_t,z1,z2)
%uncertainty_w_ThetaD
%    w_Theta_D = uncertainty_w_ThetaD(ETA_T,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    16-Feb-2025 11:06:20

t2 = z1.*5.689547574325928;
t3 = z1.*1.048939109230633;
t4 = z2.*1.048939109230633;
t6 = z2.*7.238391693976131e-1;
t5 = -t4;
t7 = -t6;
t8 = t2+t4;
t10 = t3+t6;
t9 = t2+t5;
t11 = t3+t7;
t12 = (t8.*z1)./2.0e+1;
t14 = (t10.*z2)./2.0e+1;
t13 = (t9.*z1)./2.0e+1;
t15 = (t11.*z2)./2.0e+1;
t17 = t12+t14;
t16 = -t15;
t19 = sqrt(t17);
t18 = t13+t16;
t20 = eta_t.*t19;
t21 = sqrt(t18);
t23 = t20+4.255632481092403e-7;
t22 = eta_t.*t21;
t24 = t22+4.255632481092403e-7;
w_Theta_D = [t23;t24;t23;t24];
end
