function f = system_f(a_k,delta_k,e_psik,e_yk,h,kappa,l_f,l_r,s_k,theta,u_deltak,v_k)
%SYSTEM_F
%    F = SYSTEM_F(A_K,DELTA_K,E_PSIK,E_YK,H,KAPPA,L_F,L_R,S_K,THETA,U_DELTAK,V_K)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Feb-2025 17:51:03

t2 = tan(delta_k);
t3 = e_yk.*kappa;
t4 = l_f+l_r;
t5 = t3-1.0;
t6 = 1.0./t4;
t7 = 1.0./t5;
t8 = l_r.*t2.*t6;
t9 = atan(t8);
t10 = e_psik+t9;
t11 = cos(t10);
f = [s_k-h.*t7.*t11.*v_k;e_yk+h.*v_k.*sin(t10);e_psik+h.*(kappa.*t7.*t11.*v_k+(t8.*v_k.*1.0./sqrt(t8.^2+1.0))./l_f);v_k+a_k.*h.*theta;delta_k+h.*u_deltak];
end
