function G = system_G(a_k,h)
%system_G
%    G = system_G(A_K,H)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Feb-2025 15:32:31

G = [0.0;0.0;0.0;a_k.*h;0.0];
end
